#!/bin/bash

version=$(curl https://api.github.com/repos/ethereum/go-ethereum/releases/latest |jq '.tag_name' -r)

[ -z $version ] && exit 1

sed -i".bak" -e "s/^ENV GETH_GIT_TAG .*/ENV GETH_GIT_TAG ${version}/g" eth/Dockerfile

if ! diff eth/Dockerfile eth/Dockerfile.bak
then
    git add eth/Dockerfile
    git commit -m "Update geth version #{version}"
    git push origin master
fi
