#!/bin/bash

version=$(curl https://api.github.com/repos/ethereum/go-ethereum/releases/latest |jq '.tag_name' -r)
sed -i".bak" -e "s/^ENV GETH_GIT_TAG .*/ENV GETH_GIT_TAG ${version}/g" Dockerfile

if ! diff Dockerfile Dockerfile.bak
then
    git add Dockerfile
    git commit -m "Update geth version #{version}"
    git push origin master
fi
